server:
  port: 8083

spring:
  application:
    name: metadata-service
  datasource:
    url: jdbc:mysql://localhost:3309/metadb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/