server:
  port: 8082

spring:
  application:
    name: file-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-south-1
    stack:
      auto: false
  s3:
    bucket: docuvault-bucket

jwt:
  secret: b9h3M8vKf7N6Lk1Qp4Iw3jYx8VrP9TmcLAlwC4wZlO4=

metadata:
  url: http://localhost:8083/api/metadata
