server:
  port: 8084

spring:
  application:
    name: excel-import-service
  datasource:
    url: jdbc:mysql://localhost:3306/excel_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    region: ap-south-1
    bucket: docuvault-bucket
