server:
  port: 8084

spring:
  application:
    name: excel-import-service
  datasource:
    url: jdbc:mysql://localhost:3310/exceldb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/